from django.shortcuts import render
from .models import Utilities
import datetime

# libraries needed for the webdriver
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os
import pandas as pd
from bs4 import BeautifulSoup
import re
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC


# Create your views here.
def homepage(request):
    return render(request, 'pages/index.html', {})

def utilities(request):
    if request.method == 'POST':
        new_utilities = Utilities(utility_type = request.POST.get('utility_field'), date = request.POST.get('date_field'), amount = request.POST.get('amount_field'))
        new_utilities.save() 
        utilities_table = Utilities.objects.all()
        return render(request, 'pages/utilities.html', {"utilities_table": utilities_table})
        
    else: 
        utilities_table = Utilities.objects.all()
        return render(request, 'pages/utilities.html', {"utilities_table": utilities_table})

def groceries(request):
    if request.method == 'POST':
        chrome_options = Options()
        driver = webdriver.Chrome(chrome_options=chrome_options)
        chrome_options.add_argument('--window-size=1920x1080')
        chrome_options.add_argument('--headless')
        driver.get('https://primenow.amazon.com/home')
        driver.find_element_by_id('lsPostalCode').send_keys(request.POST.get('zip_code')) 
        driver.find_element_by_class_name('a-button-input').click()
        wait = WebDriverWait(driver, 10)
        element = wait.until(EC.element_to_be_clickable((By.XPATH, "(//div[@class='show-for-large page_header_drop_menu_trigger__triggerText__3dDUD'])[3]")))
        driver.find_element_by_xpath("(//div[@class='show-for-large page_header_drop_menu_trigger__triggerText__3dDUD'])[3]").click()
        driver.find_element_by_id('ap_email').send_keys(request.POST.get('amzn_user'))  
        driver.find_element_by_id('ap_password').send_keys(request.POST.get('amzn_pass'))
        driver.find_element_by_id('signInSubmit').click()
        driver.find_element_by_xpath("(//a[@class='a-spacing-small a-link-normal'])[1]").click()
        # Pull all of the tables from the html with the order dates
        order_dates_page = driver.page_source
        order_dates_page_soup = BeautifulSoup(order_dates_page)
        order_dates_table = order_dates_page_soup.find_all('table')
        # Parse the order dates available to find the correct number corresponding to the autogenerated btn id
        i = 0
        btn_id = 0
        order_date = 
        order_found = False
        while order_found == False:
            order_found = order_dates_table[i].find('span').text.strip('\n').strip() in order_date 
            if order_found == False:
                i += 1
                btn_id += 2
        driver.find_element_by_id('a-autoid-'+str(btn_id)+'-announce').click()
        order_page_source = driver.page_source
        driver.quit()
        return order_page_source;
                
    return render(request, 'pages/groceries.html', {})
 
