# Generated by Django 3.0.4 on 2020-03-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilities',
            old_name='utilitiy_type',
            new_name='utility_type',
        ),
    ]
