# Generated by Django 3.0.4 on 2020-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200315_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryDatesTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('tip', models.FloatField()),
                ('grocery_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItemsBuyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('per_unit_price', models.FloatField()),
                ('purchaser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryPredictionFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('purchaser', models.CharField(max_length=50)),
            ],
        ),
    ]
